// ================================
// 播放列表模块（已从主JS拆分）
// ================================
const playlist = [
    // 你的 143 首曲目数据（保留你原来的全部内容）
    { "id": 1, "cover": "占位符", "title": "孤季", "duration": "1:00", "year": "2014.1", "age": 15, "englishTitle": "1", "release": "2", "style": "3", "audio": "4", "note": "5" },
    { "id": 2, "cover": "占位符", "title": "鲁镇", "duration": "1:00", "year": "2014.2", "age": 15, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 3, "cover": "占位符", "title": "听说", "duration": "1:00", "year": "2014.4", "age": 15, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 4, "cover": "占位符", "title": "那些美好", "duration": "1:00", "year": "2014.5", "age": 15, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 5, "cover": "占位符", "title": "告白与告别", "duration": "1:00", "year": "2014.11", "age": 16, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 6, "cover": "占位符", "title": "我愿陪你颠沛流离", "duration": "1:00", "year": "2014.12", "age": 16, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 7, "cover": "占位符", "title": "圣诞孤单", "duration": "1:00", "year": "2014.12", "age": 16, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 8, "cover": "占位符", "title": "再抄写一遍", "duration": "1:00", "year": "2014.12", "age": 16, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 9, "cover": "占位符", "title": "遥远和船", "duration": "1:00", "year": "2015.12", "age": 17, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 10, "cover": "占位符", "title": "相似红豆", "duration": "1:00", "year": "2016.12", "age": 18, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 11, "cover": "占位符", "title": "天亮", "duration": "1:00", "year": "2017.12", "age": 19, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 12, "cover": "占位符", "title": "远风岛", "duration": "1:00", "year": "2018.12", "age": 20, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 13, "cover": "占位符", "title": "世界尽头的歌声", "duration": "1:00", "year": "2019.12", "age": 21, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 14, "cover": "占位符", "title": "一起回家", "duration": "1:00", "year": "2020.12", "age": 22, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 15, "cover": "占位符", "title": "怀旧先生", "duration": "1:00", "year": "2021.12", "age": 23, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 16, "cover": "占位符", "title": "雨季不再来", "duration": "1:00", "year": "2022.12", "age": 24, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 17, "cover": "占位符", "title": "此间的少年", "duration": "1:00", "year": "2023.12", "age": 25, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 18, "cover": "占位符", "title": "你还好吗", "duration": "1:00", "year": "2024.12", "age": 26, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 19, "cover": "占位符", "title": "千只鹤", "duration": "1:00", "year": "2025.12", "age": 27, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 20, "cover": "占位符", "title": "树与花", "duration": "1:00", "year": "2026.12", "age": 28, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 21, "cover": "占位符", "title": "时间游戏", "duration": "1:00", "year": "2027.12", "age": 29, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 22, "cover": "占位符", "title": "百年孤独", "duration": "1:00", "year": "2028.12", "age": 30, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 23, "cover": "占位符", "title": "折纸灯", "duration": "1:00", "year": "2029.12", "age": 31, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 24, "cover": "占位符", "title": "乌龟", "duration": "1:00", "year": "2030.12", "age": 32, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 25, "cover": "占位符", "title": "盛夏夜", "duration": "1:00", "year": "2031.12", "age": 33, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 26, "cover": "占位符", "title": "一叶不知秋", "duration": "1:00", "year": "2032.12", "age": 34, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 27, "cover": "占位符", "title": "南方以南，北方以北", "duration": "1:00", "year": "2033.12", "age": 35, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 28, "cover": "占位符", "title": "风景过后", "duration": "1:00", "year": "2034.12", "age": 36, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 29, "cover": "占位符", "title": "红色小闹钟", "duration": "1:00", "year": "2035.12", "age": 37, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 30, "cover": "占位符", "title": "小巨人", "duration": "1:00", "year": "2036.12", "age": 38, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 31, "cover": "占位符", "title": "你", "duration": "1:00", "year": "2037.12", "age": 39, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 32, "cover": "占位符", "title": "报答", "duration": "1:00", "year": "2038.12", "age": 40, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 33, "cover": "占位符", "title": "五月", "duration": "1:00", "year": "2039.12", "age": 41, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 34, "cover": "占位符", "title": "你是我的夏天", "duration": "1:00", "year": "2040.12", "age": 42, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 35, "cover": "占位符", "title": "礼县", "duration": "1:00", "year": "2041.12", "age": 43, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 36, "cover": "占位符", "title": "我不能用粤语祝你生日快乐", "duration": "1:00", "year": "2042.12", "age": 44, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 37, "cover": "占位符", "title": "青春絮语", "duration": "1:00", "year": "2043.12", "age": 45, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 38, "cover": "占位符", "title": "石乐志", "duration": "1:00", "year": "2044.12", "age": 46, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 39, "cover": "占位符", "title": "宁波", "duration": "1:00", "year": "2045.12", "age": 47, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 40, "cover": "占位符", "title": "池年", "duration": "1:00", "year": "2046.12", "age": 48, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 41, "cover": "占位符", "title": "方十八", "duration": "1:00", "year": "2047.12", "age": 49, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 42, "cover": "占位符", "title": "请回答1999", "duration": "1:00", "year": "2048.12", "age": 50, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 43, "cover": "占位符", "title": "糖果", "duration": "1:00", "year": "2049.12", "age": 51, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 44, "cover": "占位符", "title": "我亦是行人", "duration": "1:00", "year": "2050.12", "age": 52, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 45, "cover": "占位符", "title": "第几个七夕", "duration": "1:00", "year": "2051.12", "age": 53, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 46, "cover": "占位符", "title": "夏日纪事", "duration": "1:00", "year": "2052.12", "age": 54, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 47, "cover": "占位符", "title": "我亦飘零久", "duration": "1:00", "year": "2053.12", "age": 55, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 48, "cover": "占位符", "title": "山城啤酒", "duration": "1:00", "year": "2054.12", "age": 56, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 49, "cover": "占位符", "title": "冷暖", "duration": "1:00", "year": "2055.12", "age": 57, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 50, "cover": "占位符", "title": "深夜食堂", "duration": "1:00", "year": "2056.12", "age": 58, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 51, "cover": "占位符", "title": "Hey", "duration": "1:00", "year": "2057.12", "age": 59, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 52, "cover": "占位符", "title": "当流星划过上海", "duration": "1:00", "year": "2058.12", "age": 60, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 53, "cover": "占位符", "title": "山雨欲来风满楼2019", "duration": "1:00", "year": "2059.12", "age": 61, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 54, "cover": "占位符", "title": "元灯夜", "duration": "1:00", "year": "2060.12", "age": 62, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 55, "cover": "占位符", "title": "野马浜之歌", "duration": "1:00", "year": "2061.12", "age": 63, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 56, "cover": "占位符", "title": "塞壬", "duration": "1:00", "year": "2062.12", "age": 64, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 57, "cover": "占位符", "title": "灰尘童话", "duration": "1:00", "year": "2063.12", "age": 65, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 58, "cover": "占位符", "title": "夏天再见", "duration": "1:00", "year": "2064.12", "age": 66, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 59, "cover": "占位符", "title": "混音魔王/人生无道理", "duration": "1:00", "year": "2065.12", "age": 67, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 60, "cover": "占位符", "title": "冬眠的海", "duration": "1:00", "year": "2066.12", "age": 68, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 61, "cover": "占位符", "title": "树与飞鸟", "duration": "1:00", "year": "2067.12", "age": 69, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 62, "cover": "占位符", "title": "白昼烟火", "duration": "1:00", "year": "2068.12", "age": 70, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 63, "cover": "占位符", "title": "宇宙尘埃", "duration": "1:00", "year": "2069.12", "age": 71, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 64, "cover": "占位符", "title": "你陪我多少年", "duration": "1:00", "year": "2070.12", "age": 72, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 65, "cover": "占位符", "title": "周游世界的精灵", "duration": "1:00", "year": "2071.12", "age": 73, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 66, "cover": "占位符", "title": "往事2021", "duration": "1:00", "year": "2072.12", "age": 74, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 67, "cover": "占位符", "title": "河雨", "duration": "1:00", "year": "2073.12", "age": 75, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 68, "cover": "占位符", "title": "月圆", "duration": "1:00", "year": "2074.12", "age": 76, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 69, "cover": "占位符", "title": "少年具象", "duration": "1:00", "year": "2075.12", "age": 77, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 70, "cover": "占位符", "title": "外青松7990", "duration": "1:00", "year": "2076.12", "age": 78, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 71, "cover": "占位符", "title": "酣欢", "duration": "1:00", "year": "2077.12", "age": 79, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 72, "cover": "占位符", "title": "橘子辉煌", "duration": "1:00", "year": "2078.12", "age": 80, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 73, "cover": "占位符", "title": "工厂大门", "duration": "1:00", "year": "2079.12", "age": 81, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 74, "cover": "信.png", "title": "一封陌生女人的来信", "duration": "1:00", "year": "2080.12", "age": 82, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 75, "cover": "占位符", "title": "双源记", "duration": "1:00", "year": "2081.12", "age": 83, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 76, "cover": "占位符", "title": "暴风雨", "duration": "1:00", "year": "2082.12", "age": 84, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 77, "cover": "占位符", "title": "海岸线", "duration": "1:00", "year": "2083.12", "age": 85, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 78, "cover": "占位符", "title": "一年又一年", "duration": "1:00", "year": "2084.12", "age": 86, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 79, "cover": "占位符", "title": "这片土地是你的土地", "duration": "1:00", "year": "2085.12", "age": 87, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 80, "cover": "占位符", "title": "天文日记", "duration": "1:00", "year": "2086.12", "age": 88, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 81, "cover": "占位符", "title": "飞向天空的单车", "duration": "1:00", "year": "2087.12", "age": 89, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 82, "cover": "占位符", "title": "我们最后的校园民谣", "duration": "1:00", "year": "2088.12", "age": 90, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 83, "cover": "占位符", "title": "伤心旅馆", "duration": "1:00", "year": "2089.12", "age": 91, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 84, "cover": "占位符", "title": "贝壳", "duration": "1:00", "year": "2090.12", "age": 92, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 85, "cover": "占位符", "title": "零", "duration": "1:00", "year": "2091.12", "age": 93, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 86, "cover": "占位符", "title": "有爱天注定", "duration": "1:00", "year": "2092.12", "age": 94, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 87, "cover": "占位符", "title": "我是一条船", "duration": "1:00", "year": "2093.12", "age": 95, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 88, "cover": "占位符", "title": "逃亡北京", "duration": "1:00", "year": "2094.12", "age": 96, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 89, "cover": "占位符", "title": "如期归来……", "duration": "1:00", "year": "2095.12", "age": 97, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 90, "cover": "占位符", "title": "元气少女", "duration": "1:00", "year": "2096.12", "age": 98, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 91, "cover": "占位符", "title": "消失在风里的女孩", "duration": "1:00", "year": "2097.12", "age": 99, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 92, "cover": "占位符", "title": "维尼男孩", "duration": "1:00", "year": "2098.12", "age": 100, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 93, "cover": "占位符", "title": "一梦画黄粱", "duration": "1:00", "year": "2099.12", "age": 101, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 94, "cover": "占位符", "title": "幸运星", "duration": "1:00", "year": "2100.12", "age": 102, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 95, "cover": "占位符", "title": "桨声灯影里的苏州河", "duration": "1:00", "year": "2101.12", "age": 103, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 96, "cover": "占位符", "title": "夜色正好", "duration": "1:00", "year": "2102.12", "age": 104, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 97, "cover": "占位符", "title": "成年旧事", "duration": "1:00", "year": "2103.12", "age": 105, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 98, "cover": "占位符", "title": "无疾而终的夏", "duration": "1:00", "year": "2104.12", "age": 106, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 99, "cover": "占位符", "title": "春天的一场雪", "duration": "1:00", "year": "2105.12", "age": 107, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 100, "cover": "占位符", "title": "江上往来人", "duration": "1:00", "year": "2106.12", "age": 108, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 101, "cover": "占位符", "title": "最后一个与你互相取暖的夜晚", "duration": "1:00", "year": "2107.12", "age": 109, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 102, "cover": "占位符", "title": "海上有仙山", "duration": "1:00", "year": "2108.12", "age": 110, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 103, "cover": "picture/gaza.jpg", "title": "出加沙记", "duration": "1:00", "year": "2109.12", "age": 111, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 104, "cover": "占位符", "title": "春", "duration": "1:00", "year": "2110.12", "age": 112, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 105, "cover": "占位符", "title": "名为童年的遥远记忆", "duration": "1:00", "year": "2111.12", "age": 113, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 106, "cover": "占位符", "title": "断桨", "duration": "1:00", "year": "2112.12", "age": 114, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 107, "cover": "占位符", "title": "昆园曲", "duration": "1:00", "year": "2113.12", "age": 115, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 108, "cover": "占位符", "title": "盛世危言", "duration": "1:00", "year": "2114.12", "age": 116, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 109, "cover": "占位符", "title": "龙与少年游", "duration": "1:00", "year": "2115.12", "age": 117, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 110, "cover": "picture/summer.jpg", "title": "驶向夏日的最后一班地铁", "duration": "1:00", "year": "2116.12", "age": 118, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 111, "cover": "picture/summer.jpg", "title": "无尽夏", "duration": "1:00", "year": "2117.12", "age": 119, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 112, "cover": "picture/summer.jpg", "title": "一万个夏天", "duration": "1:00", "year": "2118.12", "age": 120, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 113, "cover": "占位符", "title": "一百年前的风", "duration": "1:00", "year": "2119.12", "age": 121, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 114, "cover": "占位符", "title": "廉价商店", "duration": "1:00", "year": "2120.12", "age": 122, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 115, "cover": "占位符", "title": "骑手典礼", "duration": "1:00", "year": "2121.12", "age": 123, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 116, "cover": "占位符", "title": "火柴塑像", "duration": "1:00", "year": "2122.12", "age": 124, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 117, "cover": "占位符", "title": "小小说", "duration": "1:00", "year": "2123.12", "age": 125, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 118, "cover": "占位符", "title": "云是一张毯", "duration": "1:00", "year": "2124.12", "age": 126, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 119, "cover": "占位符", "title": "今夜我和你", "duration": "1:00", "year": "2125.12", "age": 127, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 120, "cover": "占位符", "title": "爱与伤痕", "duration": "1:00", "year": "2126.12", "age": 128, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 121, "cover": "占位符", "title": "没有什么能够阻挡我们的重逢", "duration": "1:00", "year": "2127.12", "age": 129, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 122, "cover": "占位符", "title": "旧伤复发", "duration": "1:00", "year": "2128.12", "age": 130, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 123, "cover": "占位符", "title": "渔夫和魔鬼", "duration": "1:00", "year": "2129.12", "age": 131, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 124, "cover": "占位符", "title": "世界是一首我爱你的歌", "duration": "1:00", "year": "2130.12", "age": 132, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 125, "cover": "占位符", "title": "八月的傍晚", "duration": "1:00", "year": "2131.12", "age": 133, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 126, "cover": "占位符", "title": "思南路82号", "duration": "1:00", "year": "2132.12", "age": 134, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 127, "cover": "占位符", "title": "月河", "duration": "1:00", "year": "2133.12", "age": 135, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 128, "cover": "占位符", "title": "徕卡不值得", "duration": "1:00", "year": "2134.12", "age": 136, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 129, "cover": "占位符", "title": "新世界", "duration": "1:00", "year": "2135.12", "age": 137, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 130, "cover": "占位符", "title": "安娜堡", "duration": "1:00", "year": "2136.12", "age": 138, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 131, "cover": "占位符", "title": "走", "duration": "1:00", "year": "2137.12", "age": 139, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 132, "cover": "占位符", "title": "奔竞", "duration": "1:00", "year": "2138.12", "age": 140, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 133, "cover": "占位符", "title": "咆哮的二零年代", "duration": "1:00", "year": "2139.12", "age": 141, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 134, "cover": "占位符", "title": "上海青", "duration": "1:00", "year": "2140.12", "age": 142, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 135, "cover": "占位符", "title": "太平洋，再会", "duration": "1:00", "year": "2141.12", "age": 143, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 136, "cover": "占位符", "title": "滚石不生苔", "duration": "1:00", "year": "2142.12", "age": 144, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 137, "cover": "占位符", "title": "纳米布沙漠", "duration": "1:00", "year": "2143.12", "age": 145, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 138, "cover": "占位符", "title": "致佘山", "duration": "1:00", "year": "2144.12", "age": 146, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 139, "cover": "占位符", "title": "公正的吉里", "duration": "1:00", "year": "2145.12", "age": 147, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 140, "cover": "占位符", "title": "自然历史", "duration": "1:00", "year": "2146.12", "age": 148, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 141, "cover": "占位符", "title": "1970", "duration": "1:00", "year": "2147.12", "age": 149, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 142, "cover": "占位符", "title": "维纳斯的试炼", "duration": "1:00", "year": "2148.12", "age": 150, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" },
    { "id": 143, "cover": "占位符", "title": "Zoey", "duration": "1:00", "year": "2149.12", "age": 151, "englishTitle": "", "release": "", "style": "", "audio": "", "note": "" }  
  ];

  playlist.forEach(
    song => {
      if (!("englishTitle" in song)) song.englishTitle = "";
      if (!("release" in song)) song.release = "";
      if (!("style" in song)) song.style = "";
      if (!("audio" in song)) song.audio = "";
    }
  );
  
  // 播放列表全局可用
  window.playlist = playlist;

